[2024-09-15T23:25:17.649+0000] {processor.py:186} INFO - Started process (PID=291) to work on /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:25:17.649+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/primeira_dag.py for tasks to queue
[2024-09-15T23:25:17.651+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:25:17.650+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:25:17.652+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:25:17.652+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/primeira_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/primeira_dag.py", line 4
    with DAG() as dag:
                      ^
IndentationError: expected an indented block after 'with' statement on line 4
[2024-09-15T23:25:17.653+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:25:17.663+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/primeira_dag.py took 0.018 seconds
[2024-09-15T23:25:47.782+0000] {processor.py:186} INFO - Started process (PID=298) to work on /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:25:47.783+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/primeira_dag.py for tasks to queue
[2024-09-15T23:25:47.785+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:25:47.785+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:25:47.787+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:25:47.786+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/primeira_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/primeira_dag.py", line 4
    with DAG() as dag:
                      ^
IndentationError: expected an indented block after 'with' statement on line 4
[2024-09-15T23:25:47.787+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:25:47.798+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/primeira_dag.py took 0.019 seconds
[2024-09-15T23:26:17.916+0000] {processor.py:186} INFO - Started process (PID=305) to work on /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:26:17.916+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/primeira_dag.py for tasks to queue
[2024-09-15T23:26:17.918+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:26:17.918+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:26:17.920+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:26:17.919+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/primeira_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/primeira_dag.py", line 4
    with DAG() as dag:
                      ^
IndentationError: expected an indented block after 'with' statement on line 4
[2024-09-15T23:26:17.920+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:26:17.930+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/primeira_dag.py took 0.018 seconds
[2024-09-15T23:26:48.049+0000] {processor.py:186} INFO - Started process (PID=312) to work on /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:26:48.050+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/primeira_dag.py for tasks to queue
[2024-09-15T23:26:48.051+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:26:48.051+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:26:48.053+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:26:48.052+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/primeira_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/primeira_dag.py", line 4
    with DAG() as dag:
                      ^
IndentationError: expected an indented block after 'with' statement on line 4
[2024-09-15T23:26:48.053+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:26:48.063+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/primeira_dag.py took 0.018 seconds
[2024-09-15T23:27:18.172+0000] {processor.py:186} INFO - Started process (PID=319) to work on /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:27:18.173+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/primeira_dag.py for tasks to queue
[2024-09-15T23:27:18.174+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:27:18.174+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:27:18.176+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:27:18.175+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/primeira_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/primeira_dag.py", line 4
    with DAG() as dag:
                      ^
IndentationError: expected an indented block after 'with' statement on line 4
[2024-09-15T23:27:18.176+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:27:18.187+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/primeira_dag.py took 0.018 seconds
[2024-09-15T23:27:48.299+0000] {processor.py:186} INFO - Started process (PID=326) to work on /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:27:48.300+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/primeira_dag.py for tasks to queue
[2024-09-15T23:27:48.301+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:27:48.301+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:27:48.303+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:27:48.302+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/primeira_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/primeira_dag.py", line 4
    with DAG() as dag:
                      ^
IndentationError: expected an indented block after 'with' statement on line 4
[2024-09-15T23:27:48.303+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:27:48.314+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/primeira_dag.py took 0.018 seconds
[2024-09-15T23:28:18.434+0000] {processor.py:186} INFO - Started process (PID=333) to work on /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:28:18.435+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/primeira_dag.py for tasks to queue
[2024-09-15T23:28:18.436+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:28:18.436+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:28:18.438+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:28:18.437+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/primeira_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/primeira_dag.py", line 4
    with DAG() as dag:
                      ^
IndentationError: expected an indented block after 'with' statement on line 4
[2024-09-15T23:28:18.438+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:28:18.449+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/primeira_dag.py took 0.018 seconds
[2024-09-15T23:28:48.565+0000] {processor.py:186} INFO - Started process (PID=340) to work on /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:28:48.566+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/primeira_dag.py for tasks to queue
[2024-09-15T23:28:48.567+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:28:48.567+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:28:48.568+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:28:48.568+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/primeira_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/primeira_dag.py", line 4
    with DAG() as dag:
                      ^
IndentationError: expected an indented block after 'with' statement on line 4
[2024-09-15T23:28:48.569+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:28:48.579+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/primeira_dag.py took 0.018 seconds
[2024-09-15T23:29:18.697+0000] {processor.py:186} INFO - Started process (PID=347) to work on /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:29:18.698+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/primeira_dag.py for tasks to queue
[2024-09-15T23:29:18.699+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:29:18.699+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:29:18.701+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:29:18.700+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/primeira_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/primeira_dag.py", line 4
    with DAG() as dag:
                      ^
IndentationError: expected an indented block after 'with' statement on line 4
[2024-09-15T23:29:18.701+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:29:18.711+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/primeira_dag.py took 0.018 seconds
[2024-09-15T23:29:48.832+0000] {processor.py:186} INFO - Started process (PID=354) to work on /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:29:48.833+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/primeira_dag.py for tasks to queue
[2024-09-15T23:29:48.834+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:29:48.834+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:29:48.836+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:29:48.835+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/primeira_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/primeira_dag.py", line 4
    with DAG() as dag:
                      ^
IndentationError: expected an indented block after 'with' statement on line 4
[2024-09-15T23:29:48.836+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:29:48.847+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/primeira_dag.py took 0.018 seconds
[2024-09-15T23:30:18.969+0000] {processor.py:186} INFO - Started process (PID=361) to work on /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:30:18.969+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/primeira_dag.py for tasks to queue
[2024-09-15T23:30:18.971+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:30:18.971+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:30:18.973+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:30:18.972+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/primeira_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/primeira_dag.py", line 4
    with DAG() as dag:
                      ^
IndentationError: expected an indented block after 'with' statement on line 4
[2024-09-15T23:30:18.973+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:30:18.984+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/primeira_dag.py took 0.019 seconds
[2024-09-15T23:30:49.100+0000] {processor.py:186} INFO - Started process (PID=368) to work on /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:30:49.101+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/primeira_dag.py for tasks to queue
[2024-09-15T23:30:49.102+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:30:49.102+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:30:49.104+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:30:49.103+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/primeira_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/primeira_dag.py", line 4
    with DAG() as dag:
                      ^
IndentationError: expected an indented block after 'with' statement on line 4
[2024-09-15T23:30:49.104+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:30:49.115+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/primeira_dag.py took 0.018 seconds
[2024-09-15T23:31:19.228+0000] {processor.py:186} INFO - Started process (PID=375) to work on /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:31:19.229+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/primeira_dag.py for tasks to queue
[2024-09-15T23:31:19.230+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:31:19.230+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:31:19.232+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:31:19.231+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/primeira_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/primeira_dag.py", line 4
    with DAG() as dag:
                      ^
IndentationError: expected an indented block after 'with' statement on line 4
[2024-09-15T23:31:19.232+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:31:19.243+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/primeira_dag.py took 0.019 seconds
[2024-09-15T23:31:49.353+0000] {processor.py:186} INFO - Started process (PID=382) to work on /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:31:49.353+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/primeira_dag.py for tasks to queue
[2024-09-15T23:31:49.354+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:31:49.354+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:31:49.356+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:31:49.356+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/primeira_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/primeira_dag.py", line 4
    with DAG() as dag:
                      ^
IndentationError: expected an indented block after 'with' statement on line 4
[2024-09-15T23:31:49.357+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:31:49.367+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/primeira_dag.py took 0.018 seconds
[2024-09-15T23:32:19.482+0000] {processor.py:186} INFO - Started process (PID=389) to work on /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:32:19.482+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/primeira_dag.py for tasks to queue
[2024-09-15T23:32:19.484+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:32:19.483+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:32:19.485+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:32:19.485+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/primeira_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/primeira_dag.py", line 4
    with DAG() as dag:
                      ^
IndentationError: expected an indented block after 'with' statement on line 4
[2024-09-15T23:32:19.485+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:32:19.496+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/primeira_dag.py took 0.018 seconds
[2024-09-15T23:32:49.613+0000] {processor.py:186} INFO - Started process (PID=396) to work on /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:32:49.614+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/primeira_dag.py for tasks to queue
[2024-09-15T23:32:49.615+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:32:49.615+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:32:49.617+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:32:49.616+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/primeira_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/primeira_dag.py", line 4
    with DAG() as dag:
                      ^
IndentationError: expected an indented block after 'with' statement on line 4
[2024-09-15T23:32:49.617+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:32:49.628+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/primeira_dag.py took 0.018 seconds
[2024-09-15T23:33:19.742+0000] {processor.py:186} INFO - Started process (PID=403) to work on /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:33:19.743+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/primeira_dag.py for tasks to queue
[2024-09-15T23:33:19.745+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:33:19.744+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:33:19.746+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:33:19.746+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/primeira_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/primeira_dag.py", line 4
    with DAG() as dag:
                      ^
IndentationError: expected an indented block after 'with' statement on line 4
[2024-09-15T23:33:19.747+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:33:19.769+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/primeira_dag.py took 0.030 seconds
[2024-09-15T23:33:49.876+0000] {processor.py:186} INFO - Started process (PID=410) to work on /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:33:49.877+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/primeira_dag.py for tasks to queue
[2024-09-15T23:33:49.878+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:33:49.878+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:33:49.880+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:33:49.880+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/primeira_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/primeira_dag.py", line 4
    with DAG() as dag:
                      ^
IndentationError: expected an indented block after 'with' statement on line 4
[2024-09-15T23:33:49.880+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:33:49.891+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/primeira_dag.py took 0.018 seconds
[2024-09-15T23:34:20.008+0000] {processor.py:186} INFO - Started process (PID=417) to work on /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:34:20.009+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/primeira_dag.py for tasks to queue
[2024-09-15T23:34:20.010+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:34:20.010+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:34:20.012+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:34:20.011+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/primeira_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/primeira_dag.py", line 4
    with DAG() as dag:
                      ^
IndentationError: expected an indented block after 'with' statement on line 4
[2024-09-15T23:34:20.012+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:34:20.022+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/primeira_dag.py took 0.018 seconds
[2024-09-15T23:34:50.145+0000] {processor.py:186} INFO - Started process (PID=424) to work on /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:34:50.145+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/primeira_dag.py for tasks to queue
[2024-09-15T23:34:50.147+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:34:50.147+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:34:50.149+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:34:50.148+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/primeira_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/primeira_dag.py", line 4
    with DAG() as dag:
                      ^
IndentationError: expected an indented block after 'with' statement on line 4
[2024-09-15T23:34:50.149+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:34:50.159+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/primeira_dag.py took 0.018 seconds
[2024-09-15T23:35:20.288+0000] {processor.py:186} INFO - Started process (PID=431) to work on /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:35:20.289+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/primeira_dag.py for tasks to queue
[2024-09-15T23:35:20.291+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:35:20.291+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:35:20.294+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:35:20.293+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/primeira_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/primeira_dag.py", line 4
    with DAG() as dag:
                      ^
IndentationError: expected an indented block after 'with' statement on line 4
[2024-09-15T23:35:20.295+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:35:20.313+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/primeira_dag.py took 0.032 seconds
[2024-09-15T23:35:50.421+0000] {processor.py:186} INFO - Started process (PID=438) to work on /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:35:50.422+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/primeira_dag.py for tasks to queue
[2024-09-15T23:35:50.423+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:35:50.423+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:35:50.425+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:35:50.424+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/primeira_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/primeira_dag.py", line 4
    with DAG() as dag:
                      ^
IndentationError: expected an indented block after 'with' statement on line 4
[2024-09-15T23:35:50.425+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:35:50.437+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/primeira_dag.py took 0.020 seconds
[2024-09-15T23:36:08.511+0000] {processor.py:186} INFO - Started process (PID=445) to work on /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:36:08.512+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/primeira_dag.py for tasks to queue
[2024-09-15T23:36:08.514+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:36:08.513+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:36:08.516+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:36:08.515+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/primeira_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/primeira_dag.py", line 4, in <module>
    with DAG(
         ^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'scheduler_interval'
[2024-09-15T23:36:08.516+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:36:08.527+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/primeira_dag.py took 0.020 seconds
[2024-09-15T23:36:38.649+0000] {processor.py:186} INFO - Started process (PID=452) to work on /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:36:38.650+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/primeira_dag.py for tasks to queue
[2024-09-15T23:36:38.652+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:36:38.651+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:36:38.654+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:36:38.653+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/primeira_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/primeira_dag.py", line 4, in <module>
    with DAG(
         ^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'scheduler_interval'
[2024-09-15T23:36:38.654+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:36:38.665+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/primeira_dag.py took 0.019 seconds
[2024-09-15T23:37:08.777+0000] {processor.py:186} INFO - Started process (PID=459) to work on /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:37:08.777+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/primeira_dag.py for tasks to queue
[2024-09-15T23:37:08.779+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:37:08.779+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:37:08.781+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:37:08.780+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/primeira_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/primeira_dag.py", line 4, in <module>
    with DAG(
         ^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'scheduler_interval'
[2024-09-15T23:37:08.781+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:37:08.791+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/primeira_dag.py took 0.018 seconds
[2024-09-15T23:37:28.872+0000] {processor.py:186} INFO - Started process (PID=466) to work on /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:37:28.873+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/primeira_dag.py for tasks to queue
[2024-09-15T23:37:28.874+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:37:28.874+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:37:28.876+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:37:28.875+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/primeira_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/primeira_dag.py", line 11, in <module>
    with DAG(
         ^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'scheduler_interval'
[2024-09-15T23:37:28.876+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:37:28.888+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/primeira_dag.py took 0.020 seconds
[2024-09-15T23:37:59.006+0000] {processor.py:186} INFO - Started process (PID=473) to work on /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:37:59.006+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/primeira_dag.py for tasks to queue
[2024-09-15T23:37:59.008+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:37:59.007+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:37:59.009+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:37:59.009+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/primeira_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/primeira_dag.py", line 11, in <module>
    with DAG(
         ^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'scheduler_interval'
[2024-09-15T23:37:59.010+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:37:59.020+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/primeira_dag.py took 0.018 seconds
[2024-09-15T23:38:29.135+0000] {processor.py:186} INFO - Started process (PID=480) to work on /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:38:29.136+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/primeira_dag.py for tasks to queue
[2024-09-15T23:38:29.137+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:38:29.137+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:38:29.139+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:38:29.138+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/primeira_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/primeira_dag.py", line 11, in <module>
    with DAG(
         ^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'scheduler_interval'
[2024-09-15T23:38:29.139+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:38:29.150+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/primeira_dag.py took 0.018 seconds
[2024-09-15T23:38:59.266+0000] {processor.py:186} INFO - Started process (PID=487) to work on /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:38:59.266+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/primeira_dag.py for tasks to queue
[2024-09-15T23:38:59.268+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:38:59.268+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:38:59.270+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:38:59.269+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/primeira_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/primeira_dag.py", line 11, in <module>
    with DAG(
         ^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'scheduler_interval'
[2024-09-15T23:38:59.270+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:38:59.282+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/primeira_dag.py took 0.020 seconds
[2024-09-15T23:39:29.400+0000] {processor.py:186} INFO - Started process (PID=494) to work on /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:39:29.400+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/primeira_dag.py for tasks to queue
[2024-09-15T23:39:29.402+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:39:29.401+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:39:29.403+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:39:29.403+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/primeira_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/primeira_dag.py", line 11, in <module>
    with DAG(
         ^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'scheduler_interval'
[2024-09-15T23:39:29.404+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:39:29.414+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/primeira_dag.py took 0.018 seconds
[2024-09-15T23:39:59.536+0000] {processor.py:186} INFO - Started process (PID=501) to work on /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:39:59.537+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/primeira_dag.py for tasks to queue
[2024-09-15T23:39:59.538+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:39:59.538+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:39:59.540+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:39:59.539+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/primeira_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/primeira_dag.py", line 11, in <module>
    with DAG(
         ^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'scheduler_interval'
[2024-09-15T23:39:59.540+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:39:59.551+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/primeira_dag.py took 0.018 seconds
[2024-09-15T23:40:29.667+0000] {processor.py:186} INFO - Started process (PID=508) to work on /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:40:29.668+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/primeira_dag.py for tasks to queue
[2024-09-15T23:40:29.669+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:40:29.669+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:40:29.671+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:40:29.670+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/primeira_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/primeira_dag.py", line 11, in <module>
    with DAG(
         ^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'scheduler_interval'
[2024-09-15T23:40:29.671+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:40:29.682+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/primeira_dag.py took 0.019 seconds
[2024-09-15T23:40:59.794+0000] {processor.py:186} INFO - Started process (PID=515) to work on /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:40:59.795+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/primeira_dag.py for tasks to queue
[2024-09-15T23:40:59.796+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:40:59.796+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:40:59.798+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:40:59.797+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/primeira_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/primeira_dag.py", line 11, in <module>
    with DAG(
         ^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'scheduler_interval'
[2024-09-15T23:40:59.798+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:40:59.808+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/primeira_dag.py took 0.018 seconds
[2024-09-15T23:41:29.912+0000] {processor.py:186} INFO - Started process (PID=522) to work on /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:41:29.912+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/primeira_dag.py for tasks to queue
[2024-09-15T23:41:29.913+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:41:29.913+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:41:29.915+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:41:29.915+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/primeira_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/primeira_dag.py", line 11, in <module>
    with DAG(
         ^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'scheduler_interval'
[2024-09-15T23:41:29.916+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:41:29.928+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/primeira_dag.py took 0.020 seconds
[2024-09-15T23:42:00.029+0000] {processor.py:186} INFO - Started process (PID=529) to work on /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:42:00.030+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/primeira_dag.py for tasks to queue
[2024-09-15T23:42:00.032+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:42:00.031+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:42:00.033+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:42:00.033+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/primeira_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/primeira_dag.py", line 11, in <module>
    with DAG(
         ^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'scheduler_interval'
[2024-09-15T23:42:00.034+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:42:00.045+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/primeira_dag.py took 0.019 seconds
[2024-09-15T23:42:30.155+0000] {processor.py:186} INFO - Started process (PID=536) to work on /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:42:30.155+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/primeira_dag.py for tasks to queue
[2024-09-15T23:42:30.157+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:42:30.156+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:42:30.159+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:42:30.158+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/primeira_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/primeira_dag.py", line 11, in <module>
    with DAG(
         ^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'scheduler_interval'
[2024-09-15T23:42:30.159+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:42:30.170+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/primeira_dag.py took 0.019 seconds
[2024-09-15T23:43:00.273+0000] {processor.py:186} INFO - Started process (PID=543) to work on /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:43:00.274+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/primeira_dag.py for tasks to queue
[2024-09-15T23:43:00.275+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:43:00.275+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:43:00.277+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:43:00.276+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/primeira_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/primeira_dag.py", line 11, in <module>
    with DAG(
         ^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'scheduler_interval'
[2024-09-15T23:43:00.277+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:43:00.288+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/primeira_dag.py took 0.018 seconds
[2024-09-15T23:43:30.397+0000] {processor.py:186} INFO - Started process (PID=550) to work on /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:43:30.397+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/primeira_dag.py for tasks to queue
[2024-09-15T23:43:30.399+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:43:30.399+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:43:30.402+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:43:30.400+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/primeira_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/primeira_dag.py", line 11, in <module>
    with DAG(
         ^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'scheduler_interval'
[2024-09-15T23:43:30.402+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:43:30.413+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/primeira_dag.py took 0.020 seconds
[2024-09-15T23:44:00.511+0000] {processor.py:186} INFO - Started process (PID=557) to work on /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:44:00.545+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/primeira_dag.py for tasks to queue
[2024-09-15T23:44:00.547+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:44:00.547+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:44:00.549+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:44:00.548+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/primeira_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/primeira_dag.py", line 11, in <module>
    with DAG(
         ^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'scheduler_interval'
[2024-09-15T23:44:00.549+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:44:00.695+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/primeira_dag.py took 0.187 seconds
[2024-09-15T23:44:30.806+0000] {processor.py:186} INFO - Started process (PID=564) to work on /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:44:30.806+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/primeira_dag.py for tasks to queue
[2024-09-15T23:44:30.807+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:44:30.807+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:44:30.809+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:44:30.809+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/primeira_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/primeira_dag.py", line 11, in <module>
    with DAG(
         ^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'scheduler_interval'
[2024-09-15T23:44:30.809+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:44:30.844+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/primeira_dag.py took 0.043 seconds
[2024-09-15T23:45:00.914+0000] {processor.py:186} INFO - Started process (PID=571) to work on /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:45:00.915+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/primeira_dag.py for tasks to queue
[2024-09-15T23:45:00.916+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:45:00.916+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:45:00.918+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:45:00.917+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/primeira_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/primeira_dag.py", line 11, in <module>
    with DAG(
         ^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'scheduler_interval'
[2024-09-15T23:45:00.918+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:45:00.930+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/primeira_dag.py took 0.021 seconds
[2024-09-15T23:45:31.061+0000] {processor.py:186} INFO - Started process (PID=578) to work on /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:45:31.062+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/primeira_dag.py for tasks to queue
[2024-09-15T23:45:31.063+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:45:31.063+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:45:31.065+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:45:31.064+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/primeira_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/primeira_dag.py", line 11, in <module>
    with DAG(
         ^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'scheduler_interval'
[2024-09-15T23:45:31.065+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:45:31.100+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/primeira_dag.py took 0.043 seconds
[2024-09-15T23:46:35.088+0000] {processor.py:186} INFO - Started process (PID=44) to work on /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:46:35.089+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/primeira_dag.py for tasks to queue
[2024-09-15T23:46:35.090+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:46:35.090+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:46:35.092+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:46:35.092+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/primeira_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/primeira_dag.py", line 11, in <module>
    with DAG(
         ^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'scheduler_interval'
[2024-09-15T23:46:35.093+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:46:35.103+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/primeira_dag.py took 0.019 seconds
[2024-09-15T23:47:05.207+0000] {processor.py:186} INFO - Started process (PID=51) to work on /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:47:05.236+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/primeira_dag.py for tasks to queue
[2024-09-15T23:47:05.238+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:47:05.238+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:47:05.278+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:47:05.239+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/primeira_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/primeira_dag.py", line 11, in <module>
    with DAG(
         ^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'scheduler_interval'
[2024-09-15T23:47:05.279+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:47:05.366+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/primeira_dag.py took 0.163 seconds
[2024-09-15T23:47:35.473+0000] {processor.py:186} INFO - Started process (PID=64) to work on /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:47:35.478+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/primeira_dag.py for tasks to queue
[2024-09-15T23:47:35.479+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:47:35.479+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:47:35.488+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:47:35.483+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/primeira_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/primeira_dag.py", line 11, in <module>
    with DAG(
         ^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'scheduler_interval'
[2024-09-15T23:47:35.488+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:47:35.500+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/primeira_dag.py took 0.030 seconds
[2024-09-15T23:48:05.582+0000] {processor.py:186} INFO - Started process (PID=71) to work on /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:48:05.599+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/primeira_dag.py for tasks to queue
[2024-09-15T23:48:05.601+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:48:05.600+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:48:05.602+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:48:05.602+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/primeira_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/primeira_dag.py", line 11, in <module>
    with DAG(
         ^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'scheduler_interval'
[2024-09-15T23:48:05.603+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:48:05.651+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/primeira_dag.py took 0.072 seconds
[2024-09-15T23:48:35.700+0000] {processor.py:186} INFO - Started process (PID=72) to work on /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:48:35.701+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/primeira_dag.py for tasks to queue
[2024-09-15T23:48:35.702+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:48:35.702+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:48:35.704+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:48:35.703+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/primeira_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/primeira_dag.py", line 11, in <module>
    with DAG(
         ^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'scheduler_interval'
[2024-09-15T23:48:35.704+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:48:35.715+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/primeira_dag.py took 0.019 seconds
[2024-09-15T23:49:05.813+0000] {processor.py:186} INFO - Started process (PID=79) to work on /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:49:05.814+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/primeira_dag.py for tasks to queue
[2024-09-15T23:49:05.815+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:49:05.815+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:49:05.817+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:49:05.816+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/primeira_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/primeira_dag.py", line 11, in <module>
    with DAG(
         ^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'scheduler_interval'
[2024-09-15T23:49:05.817+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:49:05.838+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/primeira_dag.py took 0.030 seconds
[2024-09-15T23:49:35.937+0000] {processor.py:186} INFO - Started process (PID=86) to work on /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:49:35.941+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/primeira_dag.py for tasks to queue
[2024-09-15T23:49:35.942+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:49:35.942+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:49:35.944+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:49:35.943+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/primeira_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/primeira_dag.py", line 11, in <module>
    with DAG(
         ^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'scheduler_interval'
[2024-09-15T23:49:35.944+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:49:35.972+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/primeira_dag.py took 0.039 seconds
[2024-09-15T23:50:06.059+0000] {processor.py:186} INFO - Started process (PID=93) to work on /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:50:06.078+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/primeira_dag.py for tasks to queue
[2024-09-15T23:50:06.080+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:50:06.080+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:50:06.082+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:50:06.081+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/primeira_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/primeira_dag.py", line 11, in <module>
    with DAG(
         ^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'scheduler_interval'
[2024-09-15T23:50:06.082+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:50:06.154+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/primeira_dag.py took 0.098 seconds
[2024-09-15T23:50:36.197+0000] {processor.py:186} INFO - Started process (PID=100) to work on /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:50:36.269+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/primeira_dag.py for tasks to queue
[2024-09-15T23:50:36.271+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:50:36.271+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:50:36.273+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:50:36.272+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/primeira_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/primeira_dag.py", line 11, in <module>
    with DAG(
         ^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'scheduler_interval'
[2024-09-15T23:50:36.273+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:50:36.354+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/primeira_dag.py took 0.161 seconds
[2024-09-15T23:51:06.466+0000] {processor.py:186} INFO - Started process (PID=107) to work on /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:51:06.472+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/primeira_dag.py for tasks to queue
[2024-09-15T23:51:06.473+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:51:06.473+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:51:06.475+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:51:06.474+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/primeira_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/primeira_dag.py", line 11, in <module>
    with DAG(
         ^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'scheduler_interval'
[2024-09-15T23:51:06.475+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:51:06.549+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/primeira_dag.py took 0.086 seconds
[2024-09-15T23:51:36.592+0000] {processor.py:186} INFO - Started process (PID=114) to work on /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:51:36.594+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/primeira_dag.py for tasks to queue
[2024-09-15T23:51:36.596+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:51:36.596+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:51:36.598+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:51:36.597+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/primeira_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/primeira_dag.py", line 11, in <module>
    with DAG(
         ^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'scheduler_interval'
[2024-09-15T23:51:36.599+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:51:36.683+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/primeira_dag.py took 0.097 seconds
[2024-09-15T23:52:06.786+0000] {processor.py:186} INFO - Started process (PID=127) to work on /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:52:06.791+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/primeira_dag.py for tasks to queue
[2024-09-15T23:52:06.793+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:52:06.793+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:52:06.794+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:52:06.794+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/primeira_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/primeira_dag.py", line 11, in <module>
    with DAG(
         ^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'scheduler_interval'
[2024-09-15T23:52:06.795+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:52:06.864+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/primeira_dag.py took 0.081 seconds
[2024-09-15T23:52:36.920+0000] {processor.py:186} INFO - Started process (PID=134) to work on /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:52:36.927+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/primeira_dag.py for tasks to queue
[2024-09-15T23:52:36.928+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:52:36.928+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:52:36.930+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:52:36.930+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/primeira_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/primeira_dag.py", line 11, in <module>
    with DAG(
         ^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'scheduler_interval'
[2024-09-15T23:52:36.930+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:52:37.003+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/primeira_dag.py took 0.086 seconds
[2024-09-15T23:52:43.009+0000] {processor.py:186} INFO - Started process (PID=135) to work on /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:52:43.017+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/primeira_dag.py for tasks to queue
[2024-09-15T23:52:43.019+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:52:43.018+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:52:43.022+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:52:43.021+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/primeira_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/primeira_dag.py", line 2, in <module>
    from airflow import BashOperator
ImportError: cannot import name 'BashOperator' from 'airflow' (/home/airflow/.local/lib/python3.12/site-packages/airflow/__init__.py)
[2024-09-15T23:52:43.023+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:52:43.093+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/primeira_dag.py took 0.088 seconds
[2024-09-15T23:52:50.074+0000] {processor.py:186} INFO - Started process (PID=136) to work on /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:52:50.122+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/primeira_dag.py for tasks to queue
[2024-09-15T23:52:50.124+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:52:50.124+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:52:50.127+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:52:50.125+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/primeira_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/primeira_dag.py", line 2, in <module>
    from airflow import BashOperator
ImportError: cannot import name 'BashOperator' from 'airflow' (/home/airflow/.local/lib/python3.12/site-packages/airflow/__init__.py)
[2024-09-15T23:52:50.128+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:52:50.241+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/primeira_dag.py took 0.171 seconds
[2024-09-15T23:52:52.147+0000] {processor.py:186} INFO - Started process (PID=137) to work on /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:52:52.148+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/primeira_dag.py for tasks to queue
[2024-09-15T23:52:52.149+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:52:52.149+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:52:52.152+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:52:52.151+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/primeira_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/primeira_dag.py", line 2, in <module>
    from airflow import BashOperator
ImportError: cannot import name 'BashOperator' from 'airflow' (/home/airflow/.local/lib/python3.12/site-packages/airflow/__init__.py)
[2024-09-15T23:52:52.153+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:52:52.259+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/primeira_dag.py took 0.116 seconds
[2024-09-15T23:53:08.338+0000] {processor.py:186} INFO - Started process (PID=144) to work on /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:53:08.338+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/primeira_dag.py for tasks to queue
[2024-09-15T23:53:08.340+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:53:08.340+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:53:08.343+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:53:08.341+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/primeira_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/primeira_dag.py", line 2, in <module>
    from airflow import BashOperator
ImportError: cannot import name 'BashOperator' from 'airflow' (/home/airflow/.local/lib/python3.12/site-packages/airflow/__init__.py)
[2024-09-15T23:53:08.344+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:53:08.426+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/primeira_dag.py took 0.092 seconds
[2024-09-15T23:53:38.467+0000] {processor.py:186} INFO - Started process (PID=151) to work on /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:53:38.473+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/primeira_dag.py for tasks to queue
[2024-09-15T23:53:38.474+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:53:38.474+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:53:38.477+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:53:38.475+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/primeira_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/primeira_dag.py", line 2, in <module>
    from airflow import BashOperator
ImportError: cannot import name 'BashOperator' from 'airflow' (/home/airflow/.local/lib/python3.12/site-packages/airflow/__init__.py)
[2024-09-15T23:53:38.478+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:53:38.545+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/primeira_dag.py took 0.082 seconds
[2024-09-15T23:54:08.645+0000] {processor.py:186} INFO - Started process (PID=158) to work on /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:54:08.652+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/primeira_dag.py for tasks to queue
[2024-09-15T23:54:08.653+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:54:08.653+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:54:08.656+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:54:08.654+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/primeira_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/primeira_dag.py", line 2, in <module>
    from airflow import BashOperator
ImportError: cannot import name 'BashOperator' from 'airflow' (/home/airflow/.local/lib/python3.12/site-packages/airflow/__init__.py)
[2024-09-15T23:54:08.657+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:54:08.730+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/primeira_dag.py took 0.089 seconds
[2024-09-15T23:54:38.758+0000] {processor.py:186} INFO - Started process (PID=165) to work on /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:54:38.759+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/primeira_dag.py for tasks to queue
[2024-09-15T23:54:38.760+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:54:38.760+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:54:38.763+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:54:38.762+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/primeira_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/primeira_dag.py", line 2, in <module>
    from airflow import BashOperator
ImportError: cannot import name 'BashOperator' from 'airflow' (/home/airflow/.local/lib/python3.12/site-packages/airflow/__init__.py)
[2024-09-15T23:54:38.764+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:54:38.839+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/primeira_dag.py took 0.085 seconds
[2024-09-15T23:55:08.955+0000] {processor.py:186} INFO - Started process (PID=172) to work on /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:55:08.956+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/primeira_dag.py for tasks to queue
[2024-09-15T23:55:08.957+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:55:08.957+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:55:08.960+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:55:08.958+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/primeira_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/primeira_dag.py", line 2, in <module>
    from airflow import BashOperator
ImportError: cannot import name 'BashOperator' from 'airflow' (/home/airflow/.local/lib/python3.12/site-packages/airflow/__init__.py)
[2024-09-15T23:55:08.961+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:55:09.049+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/primeira_dag.py took 0.097 seconds
[2024-09-15T23:55:12.469+0000] {processor.py:186} INFO - Started process (PID=173) to work on /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:55:12.470+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/primeira_dag.py for tasks to queue
[2024-09-15T23:55:12.471+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:55:12.471+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:55:12.473+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:55:12.472+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/primeira_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/primeira_dag.py", line 12, in <module>
    with DAG(
         ^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'scheduler_interval'
[2024-09-15T23:55:12.473+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:55:12.540+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/primeira_dag.py took 0.075 seconds
[2024-09-15T23:55:42.608+0000] {processor.py:186} INFO - Started process (PID=180) to work on /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:55:42.616+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/primeira_dag.py for tasks to queue
[2024-09-15T23:55:42.617+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:55:42.617+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:55:42.619+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:55:42.618+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/primeira_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/primeira_dag.py", line 12, in <module>
    with DAG(
         ^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'scheduler_interval'
[2024-09-15T23:55:42.619+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:55:42.729+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/primeira_dag.py took 0.125 seconds
[2024-09-15T23:56:12.779+0000] {processor.py:186} INFO - Started process (PID=187) to work on /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:56:12.786+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/primeira_dag.py for tasks to queue
[2024-09-15T23:56:12.787+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:56:12.787+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:56:12.789+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:56:12.788+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/primeira_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/primeira_dag.py", line 12, in <module>
    with DAG(
         ^^^^
TypeError: DAG.__init__() got an unexpected keyword argument 'scheduler_interval'
[2024-09-15T23:56:12.789+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:56:12.860+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/primeira_dag.py took 0.085 seconds
[2024-09-15T23:56:40.970+0000] {processor.py:186} INFO - Started process (PID=194) to work on /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:56:40.974+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/primeira_dag.py for tasks to queue
[2024-09-15T23:56:40.976+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:56:40.976+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:56:41.493+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:56:41.151+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/primeira_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/primeira_dag.py", line 16, in <module>
    task1 = BashOperator(task_id='primeira task', bash_command="echo 'Hello World'")
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 490, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 158, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 490, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 949, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py", line 57, in validate_key
    raise AirflowException(
airflow.exceptions.AirflowException: The key 'primeira task' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2024-09-15T23:56:41.493+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:56:41.659+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/primeira_dag.py took 0.694 seconds
[2024-09-15T23:57:08.791+0000] {processor.py:186} INFO - Started process (PID=201) to work on /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:57:08.808+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/primeira_dag.py for tasks to queue
[2024-09-15T23:57:08.810+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:57:08.809+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:57:10.280+0000] {processor.py:925} INFO - DAG(s) 'primeira_dag' retrieved from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:57:11.521+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:57:11.520+0000] {override.py:1900} INFO - Created Permission View: can read on DAG:primeira_dag
[2024-09-15T23:57:11.586+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:57:11.586+0000] {override.py:1900} INFO - Created Permission View: can delete on DAG:primeira_dag
[2024-09-15T23:57:11.648+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:57:11.648+0000] {override.py:1900} INFO - Created Permission View: can edit on DAG:primeira_dag
[2024-09-15T23:57:11.765+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:57:11.765+0000] {override.py:1900} INFO - Created Permission View: can create on DAG Run:primeira_dag
[2024-09-15T23:57:11.877+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:57:11.877+0000] {override.py:1900} INFO - Created Permission View: menu access on DAG Run:primeira_dag
[2024-09-15T23:57:11.939+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:57:11.939+0000] {override.py:1900} INFO - Created Permission View: can read on DAG Run:primeira_dag
[2024-09-15T23:57:12.001+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:57:12.001+0000] {override.py:1900} INFO - Created Permission View: can delete on DAG Run:primeira_dag
[2024-09-15T23:57:12.002+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:57:12.002+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2024-09-15T23:57:12.018+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:57:12.017+0000] {dag.py:3252} INFO - Creating ORM DAG for primeira_dag
[2024-09-15T23:57:12.029+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:57:12.029+0000] {dag.py:4156} INFO - Setting next_dagrun for primeira_dag to 2024-09-15 00:00:00+00:00, run_after=2024-09-16 00:00:00+00:00
[2024-09-15T23:57:12.156+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/primeira_dag.py took 3.368 seconds
[2024-09-15T23:57:42.224+0000] {processor.py:186} INFO - Started process (PID=208) to work on /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:57:42.246+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/primeira_dag.py for tasks to queue
[2024-09-15T23:57:42.248+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:57:42.248+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:57:42.255+0000] {processor.py:925} INFO - DAG(s) 'primeira_dag' retrieved from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:57:42.271+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:57:42.270+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2024-09-15T23:57:42.285+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:57:42.285+0000] {dag.py:4156} INFO - Setting next_dagrun for primeira_dag to 2024-09-15 00:00:00+00:00, run_after=2024-09-16 00:00:00+00:00
[2024-09-15T23:57:42.442+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/primeira_dag.py took 0.222 seconds
[2024-09-15T23:57:59.341+0000] {processor.py:186} INFO - Started process (PID=209) to work on /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:57:59.370+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/primeira_dag.py for tasks to queue
[2024-09-15T23:57:59.372+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:57:59.371+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:57:59.379+0000] {processor.py:925} INFO - DAG(s) 'primeira_dag' retrieved from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:57:59.394+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:57:59.394+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2024-09-15T23:57:59.408+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:57:59.408+0000] {dag.py:4156} INFO - Setting next_dagrun for primeira_dag to 2024-09-15 00:00:00+00:00, run_after=2024-09-16 00:00:00+00:00
[2024-09-15T23:57:59.555+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/primeira_dag.py took 0.219 seconds
[2024-09-15T23:58:00.524+0000] {processor.py:186} INFO - Started process (PID=210) to work on /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:58:00.524+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/primeira_dag.py for tasks to queue
[2024-09-15T23:58:00.526+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:58:00.526+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:58:00.533+0000] {processor.py:925} INFO - DAG(s) 'primeira_dag' retrieved from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:58:00.548+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:58:00.548+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2024-09-15T23:58:00.562+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:58:00.562+0000] {dag.py:4156} INFO - Setting next_dagrun for primeira_dag to 2024-09-15 00:00:00+00:00, run_after=2024-09-16 00:00:00+00:00
[2024-09-15T23:58:00.635+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/primeira_dag.py took 0.115 seconds
[2024-09-15T23:58:30.694+0000] {processor.py:186} INFO - Started process (PID=217) to work on /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:58:30.705+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/primeira_dag.py for tasks to queue
[2024-09-15T23:58:30.706+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:58:30.706+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:58:30.714+0000] {processor.py:925} INFO - DAG(s) 'primeira_dag' retrieved from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:58:30.730+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:58:30.730+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2024-09-15T23:58:30.746+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:58:30.746+0000] {dag.py:4156} INFO - Setting next_dagrun for primeira_dag to 2024-09-15 00:00:00+00:00, run_after=2024-09-16 00:00:00+00:00
[2024-09-15T23:58:30.826+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/primeira_dag.py took 0.136 seconds
[2024-09-15T23:59:00.867+0000] {processor.py:186} INFO - Started process (PID=224) to work on /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:59:00.889+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/primeira_dag.py for tasks to queue
[2024-09-15T23:59:00.891+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:59:00.890+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:59:00.898+0000] {processor.py:925} INFO - DAG(s) 'primeira_dag' retrieved from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:59:00.913+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:59:00.913+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2024-09-15T23:59:00.926+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:59:00.926+0000] {dag.py:4156} INFO - Setting next_dagrun for primeira_dag to 2024-09-15 00:00:00+00:00, run_after=2024-09-16 00:00:00+00:00
[2024-09-15T23:59:01.022+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/primeira_dag.py took 0.159 seconds
[2024-09-15T23:59:01.964+0000] {processor.py:186} INFO - Started process (PID=225) to work on /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:59:01.965+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/primeira_dag.py for tasks to queue
[2024-09-15T23:59:01.966+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:59:01.966+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:59:01.973+0000] {processor.py:925} INFO - DAG(s) 'primeira_dag' retrieved from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:59:01.988+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:59:01.987+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2024-09-15T23:59:02.002+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:59:02.001+0000] {dag.py:4156} INFO - Setting next_dagrun for primeira_dag to 2024-09-15 00:00:00+00:00, run_after=2024-09-16 00:00:00+00:00
[2024-09-15T23:59:02.026+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/primeira_dag.py took 0.066 seconds
[2024-09-15T23:59:32.092+0000] {processor.py:186} INFO - Started process (PID=232) to work on /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:59:32.095+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/primeira_dag.py for tasks to queue
[2024-09-15T23:59:32.096+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:59:32.096+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:59:32.104+0000] {processor.py:925} INFO - DAG(s) 'primeira_dag' retrieved from /opt/airflow/dags/primeira_dag.py
[2024-09-15T23:59:32.120+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:59:32.120+0000] {dag.py:3229} INFO - Sync 1 DAGs
[2024-09-15T23:59:32.135+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:59:32.135+0000] {dag.py:4156} INFO - Setting next_dagrun for primeira_dag to 2024-09-15 00:00:00+00:00, run_after=2024-09-16 00:00:00+00:00
[2024-09-15T23:59:32.206+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/primeira_dag.py took 0.118 seconds
